start:
  path: /start
  controller: App\Controller\Api\StartGameController:start
  methods: POST
move:
  path: /move
  controller: App\Controller\Api\MoveShooterController:move
  methods: POST
shoot:
  path: /shoot
  controller: App\Controller\Api\ShootToTargetController:shoot
  methods: POST
map:
  path: /map
  controller: App\Controller\Api\MapViewController:get
  methods: GET
